SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_LIVES = 3
PLAYER_RESPAWN_DELAY = 2.0

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SCORE_SMALL = 100
SCORE_MEDIUM = 50
SCORE_LARGE = 20

PLAYER_INVINCIBILITY_TIME = 2.0
PLAYER_FLICKER_SPEED = 0.1
